# Site settings
title: Robert Drinnan
description: My Website
cover: assets/images/ship.jpeg
logo: assets/images/submarine.png
favicon: assets/images/submarine.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://www.robertdrinnan.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate

# Settings for rake task
safe: False
lsi: False
username: LanternArchon #github username
repo: LanternArchon.github.io #github repository
branch: master #branch
relative_source: ../hanuman/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  https://samanyougarg.com/
source_url:  https://github.com/LanternArchon/LanternArchon.github.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
